package org.mpardo.apps.model;

public enum EventFocus {
    REMOTE_EVENT, AMBIGUOUS_EVENT, NEW_NPC, NPC_ACTION, NPC_NEGATIVE_O_POSITIVE, MOVE_TOWARD_A_THREAD, MOVE_AWAY_FROM_A_THREAD, PC_NEGATIVE, PC_POSITIVE, CLOSE_A_THREAD, CURRENT_CONTEXT
}
